/*****************************************************************************
* @copyright
* Copyright (c) 2020-2022 Qualcomm Technologies, Inc.
* All Rights Reserved.
* Confidential and Proprietary - Qualcomm Technologies, Inc.
********************************************************************************/
#ifndef __HIJACK_DATATYPE_H__
#define __HIJACK_DATATYPE_H__

#include <stdint.h> 

/**
* Structure to store the wheel data
* linear acceleration is in the units of g/sec^2
* angular velocity is in rad/sec
* temperature is in units of deg.C
*/
typedef struct
{
   /**
   * Timestamp in microseconds synced to same clock source for the camera
   * frame timestamp.
   * timestamp_in_us = raw_timestamp_in_us + ticks_imu_clock_behind_camera_clock
   */
   uint64_t timestamp;

   /**
   * Incremental counter on the IMU data, generated by the API.
   */
   uint32_t sequence_number;

   /**
   * 
   */
   bool hijackStatus;


}  sensor_hijack;

#define BUF_SIZE 10

#endif // !__WHEEL_DATATYPE_H__

