set( ROS2_FOXY_COMMON_LIBS
  rclcpp
  rcutils
  rcpputils
  yaml
  rcl
  rcl_interfaces__rosidl_generator_c
  rcl_interfaces__rosidl_typesupport_c
  rcl_interfaces__rosidl_typesupport_cpp
  rcl_yaml_param_parser
  rosgraph_msgs__rosidl_typesupport_cpp
  nav_msgs__rosidl_typesupport_cpp
  std_msgs__rosidl_typesupport_cpp
  sensor_msgs__rosidl_typesupport_cpp
  message_filters
  ament_index_cpp
  image_transport
  class_loader
  rmw
  rmw_implementation
  rosidl_typesupport_c
  rosidl_typesupport_cpp
  rosidl_runtime_c
  rcl_logging_spdlog
  builtin_interfaces__rosidl_generator_c
  libstatistics_collector
  statistics_msgs__rosidl_typesupport_cpp
  console_bridge
  cv_bridge
  tracetools
)
